### ISSUE TITLE
move from lhttpc

### ISSUE THREAD

**Issue by andreineculau** [for-GET/katt#17]
to

* https://github.com/puzza007/katipo
* https://github.com/inaka/shotgun
* https://github.com/benoitc/hackney
* or smth else

**Comment by isakb** [comment]
Out of curiosity, what was the actual issue with lhttpc? Anything that didn't work well with it that required a move, or is it outdated or something? (Since a patch with 53 additions and 21 deletions seem like a step in the wrong direction from my point of view.)

**Comment by andreineculau** [comment]
from https://github.com/esl/lhttpc "This project is not supported anymore."

Took 1.5 years to merge the simple https://github.com/esl/lhttpc/pull/43, meanwhile we were running on some fork (not a proper lhttpc-next fork, but the fork that had this commit alone)...

The numbers are deceiving though, because the committer (me) chose the least-changes path (not out of being lazy :) but because I wanted #22 to be done before touching more the tests). Similarly, at least 6 lines are just about list-binary conversions, so one could argue "if only KATT was using binaries from the start.."

**Comment by isakb** [comment]
Fair enough :)
