### ISSUE TITLE
katt_util:is_valid does not allow additional properties

### ISSUE THREAD

**Issue by erikgustafson-klarna** [for-GET/katt#43]
After using the _set_ validation type I found an issue where set items would not match if the Actual content had additional properties.  I looked through the documentation and the tests and could not find that this behaviour was intended

This problem can be reproduce by using the APIB specification

"someList": {
      "{{type}}": "set",
      "value": [{"foo": "bar"}]
}

And try to match against the response

"someList": [
     {
    "foo", "bar",
    "foo2":"bar"
}
]

After some investigation the problem seems to be in katt_util/is_valid

If you want to I can create a failing test case for this issue

**Comment by andreineculau** [comment]
Should be fixed now, but please reopen otherwise. Thanks for the report
