### ISSUE TITLE
Using BARE_MODE

### ISSUE THREAD

**Issue by tjarvstrand** [for-GET/katt#44]
Hi,

I realized that BARE_MODE in it's current form doesn't in fact solve our problem. Since katt is a rebar dependency of our project and hackney is a subdependency it will get pulled down during the get-deps step. There is no time to create the marker file since the rebar command is atomic as far as make is concerned.

It would be nice if there were an environment variable that could be set.

**Comment by andreineculau** [comment]
Right.
Unfortunately I cannot do anything at the moment but accept a PR, if you want smth fast.
Allowing `KATT_DEV_MODE` and `KATT_BARE_MODE` as env variables equivalent to `.rebar/*` file markers in the makefile (or even better in the `rebar.config.script` - along with checking also the `CI` env variables) would get :+1: from me.

**Comment by tjarvstrand** [comment]
I have to put it in the rebar.config.script for our build to be able to pick it up. I tried it out and it works fine except for the escriptize target. I may have to put environment variable checks in both files which is a bit ugly. WDYT?

**Comment by andreineculau** [comment]
Fixed in #45
