### ISSUE TITLE
Publish to Hex.pm

### ISSUE THREAD

**Issue by brucify** [for-GET/katt#48]
Hex.pm is the package manager for the Erlang ecosystem. Uploading to Hex.pm would allow people to more easily discover this project.

https://hex.pm/packages?search=http+test

Use Rebar3 to publish. See publishing guide on http://www.rebar3.org/docs/publishing-packages

**Comment by rightfold** [comment]
s/the/a/

**Comment by brucify** [comment]
Right.

**Comment by andreineculau** [comment]
better late than never. semver tags are now automatically published to hex.pm https://hex.pm/packages/katt
