### ISSUE TITLE
float Params get multiplied by factor 10

### ISSUE THREAD

**Issue by mekanixdk** [for-GET/katt#63]
I experience that any float I assign to the test case get multiplied by a factor 10.

Test case:
`katt:run(Scenario, [{test_float, 1.23}]).`

Content of "Scenario":
```
POST http://httpbin.org/post
> Accept: application/json
> Content-Type: application/json
> User-Agent: KATT
{
    "my_float": "{{<my_float}}"
}
< 200
< Content-Type: application/json
{
    "json": {
        "my_float": 1.23,
    }
}
```

This fails with the error:
`{fail,[{not_equal,{"/body/json/my_float",1.23,12.3}}]}`

And the actual request being sent (sending to localhost listening with `nc -l`:
```
POST / HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: KATT
Host: localhost:9999
Content-Length: 24

{
    "my_float": 12.3
}
```

As you can see `1.23` have changed to `12.3`

**Comment by andreineculau** [comment]
waaat? :) confirmed :(
the katt *request* gets it wrong. it sends `12.3` when replacing `my_float` in the request body.

identified the issue in `katt_util:my_float_to_list/1`

Sorry about it, and thanks for reporting the bug!
