### ISSUE TITLE
Cannot store response Integers in Param

### ISSUE THREAD

**Issue by mekanixdk** [for-GET/katt#64]
I have this small test:

```
POST http://httpbin.org/post
> Accept: application/json
> Content-Type: application/json
> User-Agent: KATT
> Content-Type: application/json
{
    "myint":123
}
< 200
< Content-Type: application/json
{
    "json": {
        "myint": "{{>myint}}",
    }
}
```

It fails with the error

`{fail,[{not_equal,{"/body/json/myint","{{>myint}}",123}}]}`

Looks like KATT will do a comparison rather than saving the variable into `myint`.

**Comment by andreineculau** [comment]
once again, a big thank you!

**Comment by mekanixdk** [comment]
This is truly awesome. Thanks for being this quick with the fixes, saved me a lot of time. :-)
