### ISSUE TITLE
Update katt to avoid deprecated function call, in preparation for OTP25.

### ISSUE THREAD

**Issue by weetmuts** [for-GET/katt#73]
When compiling katt with the latest Erlang I get this warning:

src/katt.erl:161: http_uri:parse/1 is deprecated and will be removed in OTP 25; use use uri_string functions instead

I am not skilled enough in Erlang to create a pull request but I assume that the line:

  {ok, {Protocol0, _ , Hostname, Port, Path0, _ }} = http_uri:parse(BaseUrl),

ought to be perhaps be rewritten into something like:

 { _ , Hostname, Path0, Port, _ , Protocol0, _ } = uri_string:parse(BaseUrl)

**Comment by andreineculau** [comment]
done in b2550c6
