### ISSUE TITLE
Prepare katt for jsx 3.0

### ISSUE THREAD

**Issue by SzBencej** [for-GET/katt#74]
The default behaviour changed in jsx 3.0, jsx:decode will return with maps by default.
katt's special meaning tags does not work with maps returned by jsx:decode

Change jsx:decode function calls to explicitly return with proplists. 
This way katt can be used with jsx 3.0

**Comment by andreineculau** [comment]
Thanks for the shout. Fixed in https://github.com/for-GET/katt/commit/d1f599c56ef0d793d7cf1767651b647a38503b51
